const wordList = [
    { word: "apple", hint: "Edible fruit, not orange." },
    { word: "dog", hint: "Loyal pet with a wag." },
    { word: "house", hint: "A dwelling with a roof." },
    { word: "cat", hint: "Independent feline friend." },
    { word: "friend", hint: "Comrade in camaraderie." },
    { word: "happy", hint: "Contentment and delight." },
    { word: "book", hint: "Portable knowledge source." },
    { word: "music", hint: "Harmonious sound creation." },
    { word: "garden", hint: "Cultivated plant paradise." },
    { word: "smile", hint: "Facial expression of joy." },
    { word: "sun", hint: "Daytime's radiant star." },
    { word: "water", hint: "H2O, life's liquid." },
    { word: "time", hint: "Past, present, future." },
    { word: "school", hint: "Learning institution." },
    { word: "money", hint: "Exchange medium." },
    { word: "family", hint: "Blood and kin." },
    { word: "food", hint: "Nutritious sustenance." },
    { word: "job", hint: "Employment for earnings." },
    { word: "sleep", hint: "Nighttime rest." },
    { word: "computer", hint: "Digital device." },
    { word: "beach", hint: "Sandy seaside." },
    { word: "friend", hint: "Reliable companion." },
    { word: "morning", hint: "A new day's start." },
    { word: "camera", hint: "Photography tool." },
    { word: "dinner", hint: "Evening mealtime." },
    { word: "party", hint: "Social festivity." },
    { word: "love", hint: "Deep affection and care." },
    { word: "color", hint: "Visual spectrum." },
    { word: "flower", hint: "Blossoming plant." },
    { word: "car", hint: "Road vehicle." },
    { word: "park", hint: "Green space for leisure." },
    { word: "game", hint: "Entertaining pastime." },
    { word: "phone", hint: "Call and text device." },
    { word: "rain", hint: "Precipitation from above." },
    { word: "road", hint: "Path for travel." },
    { word: "tree", hint: "Tall, woody plant." },
    { word: "bike", hint: "Two-wheeled transportation." },
    { word: "child", hint: "Youthful person." },
    { word: "music", hint: "Aural delight." },
    { word: "book", hint: "Literary source." },
    { word: "door", hint: "Entry point." },
    { word: "fire", hint: "Heat and light source." },
    { word: "store", hint: "Retail outlet." },
    { word: "game", hint: "Playful diversion." },
    { word: "drink", hint: "Liquid consumption." },
    { word: "smile", hint: "Facial happiness." },
    { word: "beach", hint: "Sandy shore." },
    { word: "shoe", hint: "Footwear." },
    { word: "pen", hint: "Writing instrument." },
    { word: "money", hint: "Exchange medium." },
    { word: "job", hint: "Employment for earnings." },
    { word: "house", hint: "Residential abode." },
    { word: "food", hint: "Edible sustenance." },
    { word: "water", hint: "Life-sustaining fluid." },
    { word: "sun", hint: "Daylight source of warmth." },
    { word: "car", hint: "Road transportation." },
    { word: "tree", hint: "Tall, leafy plant." },
    { word: "sleep", hint: "Nighttime rest." },
    { word: "family", hint: "Blood-related kin." },
    { word: "morning", hint: "A new day's dawn." },
    { word: "book", hint: "Literary knowledge." },
    { word: "computer", hint: "Digital machine." },
    { word: "camera", hint: "Photographic tool." },
    { word: "garden", hint: "Botanical haven." },
    { word: "music", hint: "Auditory pleasure." },
    { word: "phone", hint: "Calling device." },
    { word: "rain", hint: "Moisture from the sky." },
    { word: "road", hint: "Path for journeys." },
    { word: "friend", hint: "Trusted comrade." },
    { word: "fire", hint: "Combustion's warmth." },
    { word: "school", hint: "Institution of learning." },
    { word: "party", hint: "Social celebration." },
    { word: "dinner", hint: "Evening repast." },
    { word: "camera", hint: "Photographic tool." },
    { word: "bike", hint: "Two-wheeled transport." },
    { word: "computer", hint: "Digital device." },
    { word: "love", hint: "Deep affection." },
    { word: "color", hint: "Visual spectrum." },
    { word: "flower", hint: "Blooming plant." },
];
